### PR TITLE
fix: upgrade bevy 0.12

### PR DESCRIPTION
**Pull request by pietrosophya**
Upgrades the code to Bevy 0.12

### CODE REVIEW

**Comment by Toqozz** [comment]
Thanks for this.  I'll take a proper look tomorrow and make sure everything runs fine, but should be good.

Could you also update the version table in the README?

**Comment by pietrosophya** [comment]
> Thanks for this. I'll take a proper look tomorrow and make sure everything runs fine, but should be good.
> 
> Could you also update the version table in the README?

Done 😉

**Comment by IamTheCarl** [comment]
I too am interested in seeing debug lines on 0.12, so I cloned the repo for this PR and tried it.
I did not get the error you got on any of the examples. Instead it just worked. The only hickup was that I needed to switch to the `fix/upgrade-bevy-0.12` branch.

Could you verify that the examples don't work for you after switching to that branch?

**Comment by Toqozz** [comment]
This does indeed seem to work now.  Sorry for the delay.  I've merged it manually since I had to do some commits to update the readme etc.

Thank you!

**Pull request closed without merging**
